/*
**  mod_sstats.c -- Apache sample sstats module
**  [Autogenerated via ``apxs -n sstats -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_sstats.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /sstats in as follows:
**
**    #   apache2.conf
**    LoadModule sstats_module modules/mod_sstats.so
**    <Location /sstats>
**    SetHandler sstats
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /sstats and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/sstats
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_sstats.c
*/

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"

#include "ap_config.h"

const int BUFFER_SIZE = 1024 * 256;

void exec(const char *cmd, char *result) {
  const size_t STACK_BUF_SIZE = 1024 * 128;
  FILE *pipe = popen(cmd, "r");

  char temp_buf[STACK_BUF_SIZE];
  while (fgets(temp_buf, STACK_BUF_SIZE, pipe) != NULL) {
    strcat(result, temp_buf);
  }

  pclose(pipe);
}

/* The sample content handler */
static int sstats_handler(request_rec *r) {
  if (strcmp(r->handler, "sstats")) {
    return DECLINED;
  }
  r->content_type = "text/html";

  if (!r->header_only) {
    char *res = malloc(BUFFER_SIZE + 1);
    memset(res, 0, BUFFER_SIZE * sizeof(char));

    strcat(res, "<style> * { background-color: #1e1e1e; color: #c9d4d4; font-family: \"Courier New\";} </style>");
    strcat(res, "<PRE>");

    exec("w", res);
    strcat(res, "\n");

    exec("free -h", res);
    strcat(res, "\n");

    exec("df -h", res);
    strcat(res, "\n");

    exec("uname -a", res);
    strcat(res, "\n");

    exec("lsb_release -a", res);
    strcat(res, "\n");

    strcat(res, "Temperatures\n");
    exec("cat /sys/class/thermal/thermal_zone?/temp", res);
    strcat(res, "\n");

    strcat(res, "Upgradeable packages\n");
    exec("apt list --upgradeable", res);

    strcat(res, "\nRunning processes\n");
    exec("top -b -n 1", res);

    strcat(res, "\nApache access log\n");
    exec("tail -n 100 /var/log/apache2/access.log.1", res);
    exec("tail -n 100 /var/log/apache2/access.log", res);

    strcat(res, "</PRE>");

    ap_rputs(res, r);
    free(res);
  }
  return OK;
}

static void sstats_register_hooks(apr_pool_t *p) {
  ap_hook_handler(sstats_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA sstats_module = {
    STANDARD20_MODULE_STUFF,
    NULL,                 /* create per-dir    config structures */
    NULL,                 /* merge  per-dir    config structures */
    NULL,                 /* create per-server config structures */
    NULL,                 /* merge  per-server config structures */
    NULL,                 /* table of config file commands       */
    sstats_register_hooks /* register hooks                      */
};
